In [9]:
from transformers import AutoTokenizer, AutoModelForCausalLM
org_tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-4b-it")
org_tokenizer.save_pretrained("gemma3")

('gemma3/tokenizer_config.json',
 'gemma3/chat_template.jinja',
 'gemma3/tokenizer.json')

In [14]:
org_model = AutoModelForCausalLM.from_pretrained("google/embeddinggemma-300m")
org_model.save_pretrained("gemma3")
source_embeddings = org_model.model.embed_tokens.weight.to(org_model.device)
source_embeddings.shape[1]

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

768

In [13]:
org_model = AutoModelForCausalLM.from_pretrained("gemma3_cloned")
source_embeddings = org_model.model.embed_tokens.weight.to(org_model.device)
source_embeddings.shape

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

torch.Size([32768, 768])

In [7]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("alibayram/tabi-downstream-task-embeddinggemma")

query = "Yapay zeka gelecekte önemli olacak"
documents = [
    "Makine öğrenmesi geleceğin teknolojisidir",
    "Bugün hava çok güzel",
    "Türkiye'de turizm sektörü büyüyor"
]

query_embedding = model.encode(query)
doc_embeddings = model.encode(documents)

similarities = model.similarity(query_embedding, doc_embeddings)
print(similarities)

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

tensor([[0.3616, 0.2702, 0.3002]])


In [7]:
import json

with open("org_vocab.json", "w", encoding="utf-8") as f:
  json.dump(org_tokenizer.get_vocab(), f, ensure_ascii=False, indent=4)



In [4]:
# Import the module directly
import turkish_tokenizer as tt

tokenizer = tt.TurkishTokenizer()

text = "yapılırken kırılırken okuyor söylüyordu başlanmıştır bilindik Ankara'yla renga renk Türkiye'nin Türkiye'nin Türkiye'de"

tokens = tokenizer.tokenize(text)
ids = tokenizer.encode(text)

print(tokens)
print(ids)
print(tokenizer.decode(ids))

[' yapılır', 'ken', ' kır', 'ı', 'lır', 'ken', ' oku', 'yor', ' söylü', 'yor', 'du', ' başla', 'n', 'mış', 'tır', ' bilin', 'di', 'k', '<uppercase>', ' ankara', "'", 'yla', ' reng', 'a', ' renk', '<uppercase>', ' türkiye', "'", 'nin', '<uppercase>', ' türkiye', "'", 'nin', '<uppercase>', ' türkiye', "'", 'de']
[19767, 20007, 3766, 20034, 20071, 20007, 2656, 20041, 2306, 20041, 20026, 2206, 20040, 20016, 20028, 19736, 20026, 20108, 0, 3399, 20078, 20023, 245, 20037, 245, 0, 4563, 20078, 20022, 0, 4563, 20078, 20022, 0, 4563, 20078, 20024]
 yapılırkan kırılırkan okuyor söylüyordu başlanmüştür bilindük ankara'la renga renk türkiye'nın türkiye'nın türkiye'da


In [8]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("gemma3_cloned", custom_tokenizer=tokenizer)

query = "Yapay zeka gelecekte önemli olacak"
documents = [
    "Makine öğrenmesi geleceğin teknolojisidir",
    "Bugün hava çok güzel",
    "Türkiye'de turizm sektörü büyüyor"
]

query_embedding = model.encode(query)
doc_embeddings = model.encode(documents)

similarities = model.similarity(query_embedding, doc_embeddings)
print(similarities)

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

tensor([[0.3636, 0.3003, 0.1316]])


In [9]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("magibu_cloned", custom_tokenizer=tokenizer)

query = "Yapay zeka gelecekte önemli olacak"
documents = [
    "Makine öğrenmesi geleceğin teknolojisidir",
    "Bugün hava çok güzel",
    "Türkiye'de turizm sektörü büyüyor"
]

query_embedding = model.encode(query)
doc_embeddings = model.encode(documents)

similarities = model.similarity(query_embedding, doc_embeddings)
print(similarities)

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

tensor([[0.4850, 0.2780, 0.2800]])


In [37]:
import json

with open("kokler.json", "r", encoding="utf-8") as f:
    kokler = json.load(f)

with open("ekler.json", "r", encoding="utf-8") as f:
    ekler = json.load(f)

len(kokler), len(ekler)

(21761, 177)

In [38]:
with open("sorted_freq_cosmos.json", "r", encoding="utf-8") as f:
    sorted_freq_cosmos = json.load(f)

len(sorted_freq_cosmos)

88885

In [39]:
last_key = list(kokler.keys())[-1]
last_id = kokler[last_key]
last_key, last_id

(' token', 19529)

In [40]:
for token, _ in sorted_freq_cosmos.items():
  if token.startswith(" ") and token.islower() and token not in kokler:
    last_id += 1
    kokler[token] = last_id
    
    if last_id > 19998:
      break

In [26]:
with open("yeni_kokler.json", "w", encoding="utf-8") as f:
    json.dump(kokler, f, ensure_ascii=False, indent=4)

In [34]:
"1".islower(), "1".isdigit(), "!".isidentifier()

(False, True, False)

In [62]:
last_key = list(ekler.keys())[-1]
last_id = ekler[last_key]
last_key, last_id

('lır', 20071)

In [53]:
2 ** 15

32768

In [63]:
bpe_tokens = {}
for token, _ in sorted_freq_cosmos.items():
  token = token.lower()
  if len(token) < 4 and token not in kokler and token not in ekler and token not in bpe_tokens:
    last_id += 1
    bpe_tokens[token] = last_id

for token, _ in sorted_freq_cosmos.items():
  token = token.lower()
  if len(token) < 5 and token not in kokler and token not in ekler and token not in bpe_tokens:
    last_id += 1
    bpe_tokens[token] = last_id

    if last_id >= 2 ** 15:
      break


len(bpe_tokens)

12697

In [ ]:
with open("yeni_bpe_tokenler.json", "w", encoding="utf-8") as f:
    json.dump(bpe_tokens, f, ensure_ascii=False, indent=4)

In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("TabiBERT")
tokenizer.vocab_size

32768

In [12]:
tokenizer.push_to_hub("alibayram/TabiBERT-tokenizer-32k")

CommitInfo(commit_url='https://huggingface.co/alibayram/TabiBERT-tokenizer-32k/commit/f18e474d7f6f6f686a0a7dda314cfb64c1d83d28', commit_message='Upload tokenizer', commit_description='', oid='f18e474d7f6f6f686a0a7dda314cfb64c1d83d28', pr_url=None, repo_url=RepoUrl('https://huggingface.co/alibayram/TabiBERT-tokenizer-32k', endpoint='https://huggingface.co', repo_type='model', repo_id='alibayram/TabiBERT-tokenizer-32k'), pr_revision=None, pr_num=None)

In [7]:
tokenizer.save_pretrained("TabiBERT")

('TabiBERT/tokenizer_config.json', 'TabiBERT/tokenizer.json')

In [14]:
tokenizer.encode(text)

[4,
 13576,
 1682,
 14817,
 686,
 1355,
 25239,
 1784,
 2519,
 22607,
 1563,
 2357,
 599,
 8956,
 268,
 13867,
 1811,
 7676,
 6003,
 2007,
 268,
 1013,
 2007,
 268,
 1013,
 2007,
 268,
 548,
 5]